export {default as Card_Slogans} from './Card_Slogans/Card_Slogans'
export {default as Card_Services} from './Card_services/Card_Services'
export {default as Curtain} from './Curtain/Curtain'
export {default as Cookies} from './Cookies/Cookies'
export {default as ScrollToTop} from './ScrollToTop.tsx'