export { default as Navbar } from "./Navbar/Navbar";
export { default as Contact } from "./Contact/Contact";
export { default as Footer } from "./Footer/Footer";
export { default as About_header } from "./About_header/About_header";
export { default as About_vision } from "./About_vision/About_vision";
export { default as About_details } from "./About_details/About_details";
export { default as About_Us } from "./About_Us/About_Us";
export { default as About_Iso } from "./About_Iso/AboutIso";
export { default as About_pay } from "./About_pay/About_pay";
export { default as About_levels } from "./About_levels/About_levels";
export { default as About_Login } from "./About_Login/About_Login";
export { default as Date_lisson_main } from "./Date_lisson_main/Date_lisson_main";
export { default as Comments } from "./Comments/Comments";
export { default as Dashboared } from "./Dashboared/Dashboared";
export { default as LoginPage } from "./LoginPage/LoginPage";
export { default as Questions_Repeat } from "./Questions_Repeat/Questions_Repeat";
export { default as Header_Questions } from "./Header_Questions/Header_Questions";
export { default as Questions_details } from "./Questions_details/Questions_details";
export { default as Articles_header } from "./Articles_header/Articles_header";
export { default as Articles_all_sections } from "./Articles_all_sections/Articles_all_sections";
export { default as Header } from "./Header/Header";
export { default as Register_header } from "./Register_header/Register_header";
export { default as Date_lisson_Header } from "./Date_lisson_Header/Date_lisson_Header";
export { default as Our_Teachers } from "./Our_Teachers/Our_Teachers";
export { default as Our_Study_materials } from "./Our_Study_materials/Our_Study_materials";
export { default as More_Services } from "./More_Services/More_Services";
export { default as Supports } from "./Supports/Supports";
export { default as Fees_material } from "./Fees_material/Fees_material";
export { default as Register_account } from "./Register_account/Register_account";
export { default as Login_user } from "./Login_user/Login_user";
export { default as Dash_user } from "./Dash_user/Dash_user";
export { default as Privacy_sec } from "./Privacy_sec/Privacy_sec";
export { default as Student_Card } from "./Student_Card/Student_Card";
// export { default as Chat } from "./chat/Chat";
// export { default as VideoCall } from "./VideoCall/VideoCall";
// export { default as MeetingNow } from "./VideoCall/MeetingNow";
// export { default as FileSharing } from "./VideoCall/FileSharing ";
export { default as Reset_password } from "./Reset_password/Reset_password";
export { default as Level_Determination } from "./Level_Determination/Level_Determination";
export { default as LevelTest } from "./Level_Determination/LevelTest";
